# Generated by Django 5.2.3 on 2025-06-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
